sudo: false
language: ruby

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - libhttp-parser-dev
      - libssh2-1-dev

install:
  - wget https://github.com/loot/metadata-validator/releases/download/0.14.1/metadata-validator.tar.xz -O - | tar -xJ --strip-components=1
  - npm install -g js-yaml

script:
  - ./metadata_validator $TRAVIS_BUILD_DIR/masterlist.yaml
  - js-yaml $TRAVIS_BUILD_DIR/masterlist.yaml > /dev/null

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
